/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.enums


import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class ParameterTypeEnum(@get:JvmName("literal") public val literal: String) : EnumType {
    OKVED("OKVED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC
    override fun getName(): String = "parameter_type_enum"
    override fun getLiteral(): String = literal
}
