/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Business(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?,
    parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?,
    aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>(
    alias,
    ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.business</code>
         */
        val BUSINESS: Business = Business()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord> = ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord::class.java

    /**
     * The column <code>public.business.id</code>.
     */
    val ID: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "")

    /**
     * The column <code>public.business.title</code>.
     */
    val TITLE: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord, String?> = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.business.description</code>.
     */
    val DESCRIPTION: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.business.is_indexed</code>.
     */
    val IS_INDEXED: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord, Boolean?> = createField(DSL.name("is_indexed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.business</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.business</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.business</code> table reference
     */
    constructor(): this(DSL.name("business"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, BUSINESS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class BusinessPath : Business, Path<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord>): super(alias, aliased)
        override fun `as`(alias: String): BusinessPath = BusinessPath(DSL.name(alias), this)
        override fun `as`(alias: Name): BusinessPath = BusinessPath(alias, this)
        override fun `as`(alias: Table<*>): BusinessPath = BusinessPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC
    override fun getIdentity(): Identity<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord, Long?> = super.getIdentity() as Identity<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord> = ru.alfahack.elephants.backend.`data`.jooq.keys.BUSINESS_PKEY

    private lateinit var _businessParameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath

    /**
     * Get the implicit to-many join path to the
     * <code>public.business_parameter_value</code> table
     */
    fun businessParameterValue(): ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath {
        if (!this::_businessParameterValue.isInitialized)
            _businessParameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath(this, null, ru.alfahack.elephants.backend.`data`.jooq.keys.BUSINESS_PARAMETER_VALUE__BUSINESS_PARAMETER_VALUE_BUSINESS_ID_FKEY.inverseKey)

        return _businessParameterValue;
    }

    val businessParameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath = businessParameterValue()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.parameter_value</code> table
     */
    val parameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath = businessParameterValue().parameterValue()
    override fun `as`(alias: String): Business = Business(DSL.name(alias), this)
    override fun `as`(alias: Name): Business = Business(alias, this)
    override fun `as`(alias: Table<*>): Business = Business(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Business = Business(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Business = Business(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Business = Business(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Business = Business(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Business = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Business = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Business = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Business = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Business = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Business = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Business = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): Business = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): Business = where(DSL.notExists(select))
}
