/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class NewsParameterValue(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?,
    parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?,
    aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>(
    alias,
    ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.news_parameter_value</code>
         */
        val NEWS_PARAMETER_VALUE: NewsParameterValue = NewsParameterValue()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord> = ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord::class.java

    /**
     * The column <code>public.news_parameter_value.news_id</code>.
     */
    val NEWS_ID: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord, Long?> = createField(DSL.name("news_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.news_parameter_value.parameter_value_id</code>.
     */
    val PARAMETER_VALUE_ID: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord, Long?> = createField(DSL.name("parameter_value_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.news_parameter_value</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.news_parameter_value</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.news_parameter_value</code> table reference
     */
    constructor(): this(DSL.name("news_parameter_value"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, NEWS_PARAMETER_VALUE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class NewsParameterValuePath : NewsParameterValue, Path<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord>): super(alias, aliased)
        override fun `as`(alias: String): NewsParameterValuePath = NewsParameterValuePath(DSL.name(alias), this)
        override fun `as`(alias: Name): NewsParameterValuePath = NewsParameterValuePath(alias, this)
        override fun `as`(alias: Table<*>): NewsParameterValuePath = NewsParameterValuePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ru.alfahack.elephants.backend.`data`.jooq.indexes.IDX_NEWS_PARAMETER_VALUE_PARAMETER_VALUE_ID)
    override fun getPrimaryKey(): UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord> = ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PARAMETER_VALUE_PKEY
    override fun getReferences(): List<ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord, *>> = listOf(ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_NEWS_ID_FKEY, ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_PARAMETER_VALUE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.news</code> table.
     */
    fun news(): ru.alfahack.elephants.backend.`data`.jooq.tables.News.NewsPath = news
    val news: ru.alfahack.elephants.backend.`data`.jooq.tables.News.NewsPath by lazy { ru.alfahack.elephants.backend.`data`.jooq.tables.News.NewsPath(this, ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_NEWS_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.parameter_value</code>
     * table.
     */
    fun parameterValue(): ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath = parameterValue
    val parameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath by lazy { ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath(this, ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_PARAMETER_VALUE_ID_FKEY, null) }
    override fun `as`(alias: String): NewsParameterValue = NewsParameterValue(DSL.name(alias), this)
    override fun `as`(alias: Name): NewsParameterValue = NewsParameterValue(alias, this)
    override fun `as`(alias: Table<*>): NewsParameterValue = NewsParameterValue(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): NewsParameterValue = NewsParameterValue(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): NewsParameterValue = NewsParameterValue(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): NewsParameterValue = NewsParameterValue(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): NewsParameterValue = NewsParameterValue(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): NewsParameterValue = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): NewsParameterValue = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): NewsParameterValue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): NewsParameterValue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): NewsParameterValue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): NewsParameterValue = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): NewsParameterValue = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): NewsParameterValue = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): NewsParameterValue = where(DSL.notExists(select))
}
