/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ParameterValue(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?,
    parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?,
    aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>(
    alias,
    ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.parameter_value</code>
         */
        val PARAMETER_VALUE: ParameterValue = ParameterValue()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord> = ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord::class.java

    /**
     * The column <code>public.parameter_value.id</code>.
     */
    val ID: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "")

    /**
     * The column <code>public.parameter_value.parameter_type</code>.
     */
    val PARAMETER_TYPE: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?> = createField(DSL.name("parameter_type"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum::class.java), this, "")

    /**
     * The column <code>public.parameter_value.parameter_value</code>.
     */
    val PARAMETER_VALUE_: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, String?> = createField(DSL.name("parameter_value"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.parameter_value</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.parameter_value</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.parameter_value</code> table reference
     */
    constructor(): this(DSL.name("parameter_value"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PARAMETER_VALUE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ParameterValuePath : ParameterValue, Path<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord>): super(alias, aliased)
        override fun `as`(alias: String): ParameterValuePath = ParameterValuePath(DSL.name(alias), this)
        override fun `as`(alias: Name): ParameterValuePath = ParameterValuePath(alias, this)
        override fun `as`(alias: Table<*>): ParameterValuePath = ParameterValuePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ru.alfahack.elephants.backend.`data`.jooq.indexes.IDX_PARAMETER_VALUE_PARAMETER_TYPE)
    override fun getIdentity(): Identity<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, Long?> = super.getIdentity() as Identity<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord> = ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_VALUE_PKEY
    override fun getReferences(): List<ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, *>> = listOf(ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_VALUE__PARAMETER_VALUE_PARAMETER_TYPE_FKEY)

    /**
     * Get the implicit join path to the <code>public.parameter_type</code>
     * table.
     */
    fun parameterType(): ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.ParameterTypePath = parameterType
    val parameterType: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.ParameterTypePath by lazy { ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.ParameterTypePath(this, ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_VALUE__PARAMETER_VALUE_PARAMETER_TYPE_FKEY, null) }

    private lateinit var _businessParameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath

    /**
     * Get the implicit to-many join path to the
     * <code>public.business_parameter_value</code> table
     */
    fun businessParameterValue(): ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath {
        if (!this::_businessParameterValue.isInitialized)
            _businessParameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath(this, null, ru.alfahack.elephants.backend.`data`.jooq.keys.BUSINESS_PARAMETER_VALUE__BUSINESS_PARAMETER_VALUE_PARAMETER_VALUE_ID_FKEY.inverseKey)

        return _businessParameterValue;
    }

    val businessParameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BusinessParameterValuePath = businessParameterValue()

    private lateinit var _newsParameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NewsParameterValuePath

    /**
     * Get the implicit to-many join path to the
     * <code>public.news_parameter_value</code> table
     */
    fun newsParameterValue(): ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NewsParameterValuePath {
        if (!this::_newsParameterValue.isInitialized)
            _newsParameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NewsParameterValuePath(this, null, ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_PARAMETER_VALUE_ID_FKEY.inverseKey)

        return _newsParameterValue;
    }

    val newsParameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NewsParameterValuePath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NewsParameterValuePath = newsParameterValue()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.business</code> table
     */
    val business: ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BusinessPath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BusinessPath = businessParameterValue().business()

    /**
     * Get the implicit many-to-many join path to the <code>public.news</code>
     * table
     */
    val news: ru.alfahack.elephants.backend.`data`.jooq.tables.News.NewsPath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.News.NewsPath = newsParameterValue().news()
    override fun `as`(alias: String): ParameterValue = ParameterValue(DSL.name(alias), this)
    override fun `as`(alias: Name): ParameterValue = ParameterValue(alias, this)
    override fun `as`(alias: Table<*>): ParameterValue = ParameterValue(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ParameterValue = ParameterValue(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ParameterValue = ParameterValue(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ParameterValue = ParameterValue(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ParameterValue = ParameterValue(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ParameterValue = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ParameterValue = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ParameterValue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ParameterValue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ParameterValue = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ParameterValue = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ParameterValue = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): ParameterValue = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): ParameterValue = where(DSL.notExists(select))
}
