/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ParameterType(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?,
    parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?,
    aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>(
    alias,
    ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.parameter_type</code>
         */
        val PARAMETER_TYPE: ParameterType = ParameterType()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord> = ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord::class.java

    /**
     * The column <code>public.parameter_type.id</code>.
     */
    val ID: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord, ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?> = createField(DSL.name("id"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum::class.java), this, "")

    /**
     * The column <code>public.parameter_type.name</code>.
     */
    val NAME: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.parameter_type.description</code>.
     */
    val DESCRIPTION: TableField<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.parameter_type</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.parameter_type</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.parameter_type</code> table reference
     */
    constructor(): this(DSL.name("parameter_type"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PARAMETER_TYPE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ParameterTypePath : ParameterType, Path<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?, parentPath: InverseForeignKey<out Record, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord>): super(alias, aliased)
        override fun `as`(alias: String): ParameterTypePath = ParameterTypePath(DSL.name(alias), this)
        override fun `as`(alias: Name): ParameterTypePath = ParameterTypePath(alias, this)
        override fun `as`(alias: Table<*>): ParameterTypePath = ParameterTypePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else ru.alfahack.elephants.backend.`data`.jooq.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord> = ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_TYPE_PKEY

    private lateinit var _parameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath

    /**
     * Get the implicit to-many join path to the
     * <code>public.parameter_value</code> table
     */
    fun parameterValue(): ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath {
        if (!this::_parameterValue.isInitialized)
            _parameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath(this, null, ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_VALUE__PARAMETER_VALUE_PARAMETER_TYPE_FKEY.inverseKey)

        return _parameterValue;
    }

    val parameterValue: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath
        get(): ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.ParameterValuePath = parameterValue()
    override fun `as`(alias: String): ParameterType = ParameterType(DSL.name(alias), this)
    override fun `as`(alias: Name): ParameterType = ParameterType(alias, this)
    override fun `as`(alias: Table<*>): ParameterType = ParameterType(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ParameterType = ParameterType(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ParameterType = ParameterType(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ParameterType = ParameterType(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ParameterType = ParameterType(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ParameterType = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ParameterType = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ParameterType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ParameterType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ParameterType = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ParameterType = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ParameterType = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): ParameterType = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): ParameterType = where(DSL.notExists(select))
}
