/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BusinessRecord() : UpdatableRecordImpl<BusinessRecord>(ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsIndexed")
    open var isIndexed: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised BusinessRecord
     */
    constructor(id: Long? = null, title: String? = null, description: String? = null, isIndexed: Boolean? = null): this() {
        this.id = id
        this.title = title
        this.description = description
        this.isIndexed = isIndexed
        resetTouchedOnNotNull()
    }
}
