/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class BusinessParameterValueRecord() : UpdatableRecordImpl<BusinessParameterValueRecord>(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE) {

    open var businessId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var parameterValueId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised BusinessParameterValueRecord
     */
    constructor(businessId: Long? = null, parameterValueId: Long? = null): this() {
        this.businessId = businessId
        this.parameterValueId = parameterValueId
        resetTouchedOnNotNull()
    }
}
