/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.records


import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class NewsRecord() : UpdatableRecordImpl<NewsRecord>(ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var text: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var date: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var origin: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsIndexed")
    open var isIndexed: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised NewsRecord
     */
    constructor(id: Long? = null, title: String? = null, text: String? = null, date: OffsetDateTime? = null, origin: String? = null, isIndexed: Boolean? = null): this() {
        this.id = id
        this.title = title
        this.text = text
        this.date = date
        this.origin = origin
        this.isIndexed = isIndexed
        resetTouchedOnNotNull()
    }
}
