/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class NewsParameterValueRecord() : UpdatableRecordImpl<NewsParameterValueRecord>(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE) {

    open var newsId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var parameterValueId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    /**
     * Create a detached, initialised NewsParameterValueRecord
     */
    constructor(newsId: Long? = null, parameterValueId: Long? = null): this() {
        this.newsId = newsId
        this.parameterValueId = parameterValueId
        resetTouchedOnNotNull()
    }
}
