/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ParameterValueRecord() : UpdatableRecordImpl<ParameterValueRecord>(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var parameterType: ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?
        set(value): Unit = set(1, value)
        get(): ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum? = get(1) as ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?

    open var parameterValue: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised ParameterValueRecord
     */
    constructor(id: Long? = null, parameterType: ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum? = null, parameterValue: String? = null): this() {
        this.id = id
        this.parameterType = parameterType
        this.parameterValue = parameterValue
        resetTouchedOnNotNull()
    }
}
