/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ParameterTypeRecord() : UpdatableRecordImpl<ParameterTypeRecord>(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE) {

    open var id: ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?
        set(value): Unit = set(0, value)
        get(): ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum? = get(0) as ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?> = super.key() as Record1<ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum?>

    /**
     * Create a detached, initialised ParameterTypeRecord
     */
    constructor(id: ru.alfahack.elephants.backend.`data`.jooq.enums.ParameterTypeEnum? = null, name: String? = null, description: String? = null): this() {
        this.id = id
        this.name = name
        this.description = description
        resetTouchedOnNotNull()
    }
}
