CREATE TYPE parameter_type_enum AS ENUM ('OKVED');

CREATE TABLE parameter_type (
    id parameter_type_enum PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);

INSERT INTO parameter_type (id, name, description)
VALUES ('OKVED', 'ОКВЭД', 'Общероссийский классификатор видов экономической деятельности');

CREATE TABLE parameter_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_type parameter_type_enum NOT NULL
        REFERENCES parameter_type (id) ON DELETE RESTRICT,
    parameter_value TEXT NOT NULL
);

CREATE INDEX idx_parameter_value_parameter_type ON parameter_value (parameter_type);

CREATE TABLE news_parameter_value (
    news_id BIGINT NOT NULL REFERENCES news (id) ON DELETE CASCADE,
    parameter_value_id BIGINT NOT NULL REFERENCES parameter_value (id) ON DELETE CASCADE,
    PRIMARY KEY (news_id, parameter_value_id)
);

CREATE INDEX idx_news_parameter_value_parameter_value_id
    ON news_parameter_value (parameter_value_id);

CREATE TABLE business_parameter_value (
    business_id BIGINT NOT NULL REFERENCES business (id) ON DELETE CASCADE,
    parameter_value_id BIGINT NOT NULL REFERENCES parameter_value (id) ON DELETE CASCADE,
    PRIMARY KEY (business_id, parameter_value_id)
);

CREATE INDEX idx_business_parameter_value_parameter_value_id
    ON business_parameter_value (parameter_value_id);
