/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), ru.alfahack.elephants.backend.`data`.jooq.DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.business</code>.
     */
    val BUSINESS: ru.alfahack.elephants.backend.`data`.jooq.tables.Business get() = ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS

    /**
     * The table <code>public.business_parameter_value</code>.
     */
    val BUSINESS_PARAMETER_VALUE: ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue get() = ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE

    /**
     * The table <code>public.news</code>.
     */
    val NEWS: ru.alfahack.elephants.backend.`data`.jooq.tables.News get() = ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS

    /**
     * The table <code>public.news_parameter_value</code>.
     */
    val NEWS_PARAMETER_VALUE: ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue get() = ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE

    /**
     * The table <code>public.parameter_type</code>.
     */
    val PARAMETER_TYPE: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType get() = ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE

    /**
     * The table <code>public.parameter_value</code>.
     */
    val PARAMETER_VALUE: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue get() = ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE

    override fun getCatalog(): Catalog = ru.alfahack.elephants.backend.`data`.jooq.DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS,
        ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE,
        ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS,
        ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE,
        ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE,
        ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE
    )
}
