@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.tables.references




/**
 * The table <code>public.business</code>.
 */
val BUSINESS: ru.alfahack.elephants.backend.`data`.jooq.tables.Business = ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS

/**
 * The table <code>public.business_parameter_value</code>.
 */
val BUSINESS_PARAMETER_VALUE: ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE

/**
 * The table <code>public.news</code>.
 */
val NEWS: ru.alfahack.elephants.backend.`data`.jooq.tables.News = ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS

/**
 * The table <code>public.news_parameter_value</code>.
 */
val NEWS_PARAMETER_VALUE: ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE

/**
 * The table <code>public.parameter_type</code>.
 */
val PARAMETER_TYPE: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType = ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE

/**
 * The table <code>public.parameter_value</code>.
 */
val PARAMETER_VALUE: ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue = ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE
