@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_BUSINESS_PARAMETER_VALUE_PARAMETER_VALUE_ID: Index = Internal.createIndex(DSL.name("idx_business_parameter_value_parameter_value_id"), ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE.PARAMETER_VALUE_ID), false)
val IDX_NEWS_PARAMETER_VALUE_PARAMETER_VALUE_ID: Index = Internal.createIndex(DSL.name("idx_news_parameter_value_parameter_value_id"), ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE.PARAMETER_VALUE_ID), false)
val IDX_PARAMETER_VALUE_PARAMETER_TYPE: Index = Internal.createIndex(DSL.name("idx_parameter_value_parameter_type"), ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE.PARAMETER_TYPE), false)
