@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package ru.alfahack.elephants.backend.`data`.jooq.keys


import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val BUSINESS_PKEY: UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord> = Internal.createUniqueKey(ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS, DSL.name("business_pkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS.ID), true)
val BUSINESS_PARAMETER_VALUE_PKEY: UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessParameterValueRecord> = Internal.createUniqueKey(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE, DSL.name("business_parameter_value_pkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE.BUSINESS_ID, ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE.PARAMETER_VALUE_ID), true)
val NEWS_PKEY: UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsRecord> = Internal.createUniqueKey(ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS, DSL.name("news_pkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS.ID), true)
val NEWS_PARAMETER_VALUE_PKEY: UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord> = Internal.createUniqueKey(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE, DSL.name("news_parameter_value_pkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE.NEWS_ID, ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE.PARAMETER_VALUE_ID), true)
val PARAMETER_TYPE_PKEY: UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord> = Internal.createUniqueKey(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE, DSL.name("parameter_type_pkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE.ID), true)
val PARAMETER_VALUE_PKEY: UniqueKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord> = Internal.createUniqueKey(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE, DSL.name("parameter_value_pkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val BUSINESS_PARAMETER_VALUE__BUSINESS_PARAMETER_VALUE_BUSINESS_ID_FKEY: ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessParameterValueRecord, ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessRecord> = Internal.createForeignKey(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE, DSL.name("business_parameter_value_business_id_fkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE.BUSINESS_ID), ru.alfahack.elephants.backend.`data`.jooq.keys.BUSINESS_PKEY, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.Business.BUSINESS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val BUSINESS_PARAMETER_VALUE__BUSINESS_PARAMETER_VALUE_PARAMETER_VALUE_ID_FKEY: ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.BusinessParameterValueRecord, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord> = Internal.createForeignKey(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE, DSL.name("business_parameter_value_parameter_value_id_fkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.BusinessParameterValue.BUSINESS_PARAMETER_VALUE.PARAMETER_VALUE_ID), ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_VALUE_PKEY, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_NEWS_ID_FKEY: ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord, ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsRecord> = Internal.createForeignKey(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE, DSL.name("news_parameter_value_news_id_fkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE.NEWS_ID), ru.alfahack.elephants.backend.`data`.jooq.keys.NEWS_PKEY, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.News.NEWS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val NEWS_PARAMETER_VALUE__NEWS_PARAMETER_VALUE_PARAMETER_VALUE_ID_FKEY: ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.NewsParameterValueRecord, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord> = Internal.createForeignKey(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE, DSL.name("news_parameter_value_parameter_value_id_fkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.NewsParameterValue.NEWS_PARAMETER_VALUE.PARAMETER_VALUE_ID), ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_VALUE_PKEY, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val PARAMETER_VALUE__PARAMETER_VALUE_PARAMETER_TYPE_FKEY: ForeignKey<ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterValueRecord, ru.alfahack.elephants.backend.`data`.jooq.tables.records.ParameterTypeRecord> = Internal.createForeignKey(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE, DSL.name("parameter_value_parameter_type_fkey"), arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterValue.PARAMETER_VALUE.PARAMETER_TYPE), ru.alfahack.elephants.backend.`data`.jooq.keys.PARAMETER_TYPE_PKEY, arrayOf(ru.alfahack.elephants.backend.`data`.jooq.tables.ParameterType.PARAMETER_TYPE.ID), true, ForeignKeyRule.RESTRICT, ForeignKeyRule.NO_ACTION)
